name = "storyteller-supabase-stories-store-169"
main = "worker.js"
compatibility_date = "2023-08-23"
kv_namespaces = [
  { binding = "STORY_CACHE", id = "cc871fba5fe04580bc1403e334d2c8d1" },
  { binding = "SECRET_CACHE", id = "118c57c55c6340868e82458efccebb24" }
]